from setuptools import setup

setup(
    name='nnPUlearning-master',
    version='',
    packages=['venv.Lib.site-packages.absl', 'venv.Lib.site-packages.absl.flags', 'venv.Lib.site-packages.absl.logging',
              'venv.Lib.site-packages.absl.testing', 'venv.Lib.site-packages.absl.third_party',
              'venv.Lib.site-packages.absl.third_party.unittest3_backport', 'venv.Lib.site-packages.gast',
              'venv.Lib.site-packages.grpc', 'venv.Lib.site-packages.grpc.beta', 'venv.Lib.site-packages.grpc._cython',
              'venv.Lib.site-packages.grpc._cython._cygrpc', 'venv.Lib.site-packages.grpc.framework',
              'venv.Lib.site-packages.grpc.framework.common', 'venv.Lib.site-packages.grpc.framework.foundation',
              'venv.Lib.site-packages.grpc.framework.interfaces',
              'venv.Lib.site-packages.grpc.framework.interfaces.base',
              'venv.Lib.site-packages.grpc.framework.interfaces.face', 'venv.Lib.site-packages.grpc.experimental',
              'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.astor', 'venv.Lib.site-packages.numpy',
              'venv.Lib.site-packages.numpy.ma', 'venv.Lib.site-packages.numpy.ma.tests',
              'venv.Lib.site-packages.numpy.doc', 'venv.Lib.site-packages.numpy.fft',
              'venv.Lib.site-packages.numpy.fft.tests', 'venv.Lib.site-packages.numpy.lib',
              'venv.Lib.site-packages.numpy.lib.tests', 'venv.Lib.site-packages.numpy.core',
              'venv.Lib.site-packages.numpy.core.tests', 'venv.Lib.site-packages.numpy.f2py',
              'venv.Lib.site-packages.numpy.f2py.tests', 'venv.Lib.site-packages.numpy.tests',
              'venv.Lib.site-packages.numpy.compat', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.testing',
              'venv.Lib.site-packages.numpy.testing.tests', 'venv.Lib.site-packages.numpy.testing.nose_tools',
              'venv.Lib.site-packages.numpy.distutils', 'venv.Lib.site-packages.numpy.distutils.tests',
              'venv.Lib.site-packages.numpy.distutils.command', 'venv.Lib.site-packages.numpy.distutils.fcompiler',
              'venv.Lib.site-packages.numpy.matrixlib', 'venv.Lib.site-packages.numpy.matrixlib.tests',
              'venv.Lib.site-packages.numpy.polynomial', 'venv.Lib.site-packages.numpy.polynomial.tests',
              'venv.Lib.site-packages.scipy', 'venv.Lib.site-packages.scipy.io', 'venv.Lib.site-packages.scipy.io.arff',
              'venv.Lib.site-packages.scipy.io.arff.tests', 'venv.Lib.site-packages.scipy.io.tests',
              'venv.Lib.site-packages.scipy.io.matlab', 'venv.Lib.site-packages.scipy.io.matlab.tests',
              'venv.Lib.site-packages.scipy.io.harwell_boeing', 'venv.Lib.site-packages.scipy.io.harwell_boeing.tests',
              'venv.Lib.site-packages.scipy.odr', 'venv.Lib.site-packages.scipy.odr.tests',
              'venv.Lib.site-packages.scipy._lib', 'venv.Lib.site-packages.scipy._lib.tests',
              'venv.Lib.site-packages.scipy.misc', 'venv.Lib.site-packages.scipy.misc.tests',
              'venv.Lib.site-packages.scipy.stats', 'venv.Lib.site-packages.scipy.stats.tests',
              'venv.Lib.site-packages.scipy.linalg', 'venv.Lib.site-packages.scipy.linalg.tests',
              'venv.Lib.site-packages.scipy.signal', 'venv.Lib.site-packages.scipy.signal.tests',
              'venv.Lib.site-packages.scipy.signal.windows', 'venv.Lib.site-packages.scipy.sparse',
              'venv.Lib.site-packages.scipy.sparse.tests', 'venv.Lib.site-packages.scipy.sparse.linalg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.tests', 'venv.Lib.site-packages.scipy.sparse.linalg.dsolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve.tests', 'venv.Lib.site-packages.scipy.sparse.csgraph',
              'venv.Lib.site-packages.scipy.sparse.csgraph.tests', 'venv.Lib.site-packages.scipy.cluster',
              'venv.Lib.site-packages.scipy.cluster.tests', 'venv.Lib.site-packages.scipy.fftpack',
              'venv.Lib.site-packages.scipy.fftpack.tests', 'venv.Lib.site-packages.scipy.ndimage',
              'venv.Lib.site-packages.scipy.ndimage.tests', 'venv.Lib.site-packages.scipy.spatial',
              'venv.Lib.site-packages.scipy.spatial.tests', 'venv.Lib.site-packages.scipy.special',
              'venv.Lib.site-packages.scipy.special.tests', 'venv.Lib.site-packages.scipy.special._precompute',
              'venv.Lib.site-packages.scipy.optimize', 'venv.Lib.site-packages.scipy.optimize._lsq',
              'venv.Lib.site-packages.scipy.optimize.tests', 'venv.Lib.site-packages.scipy.optimize._trlib',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.Lib.site-packages.scipy.constants', 'venv.Lib.site-packages.scipy.constants.tests',
              'venv.Lib.site-packages.scipy.integrate', 'venv.Lib.site-packages.scipy.integrate._ivp',
              'venv.Lib.site-packages.scipy.integrate.tests', 'venv.Lib.site-packages.scipy.interpolate',
              'venv.Lib.site-packages.scipy.interpolate.tests', 'venv.Lib.site-packages.scipy._build_utils',
              'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.tool',
              'venv.Lib.site-packages.wheel.signatures', 'venv.Lib.site-packages.google.protobuf',
              'venv.Lib.site-packages.google.protobuf.util', 'venv.Lib.site-packages.google.protobuf.pyext',
              'venv.Lib.site-packages.google.protobuf.compiler', 'venv.Lib.site-packages.google.protobuf.internal',
              'venv.Lib.site-packages.google.protobuf.internal.import_test_package', 'venv.Lib.site-packages.chainer',
              'venv.Lib.site-packages.chainer.links', 'venv.Lib.site-packages.chainer.links.loss',
              'venv.Lib.site-packages.chainer.links.caffe', 'venv.Lib.site-packages.chainer.links.caffe.protobuf3',
              'venv.Lib.site-packages.chainer.links.model', 'venv.Lib.site-packages.chainer.links.model.vision',
              'venv.Lib.site-packages.chainer.links.theano', 'venv.Lib.site-packages.chainer.links.activation',
              'venv.Lib.site-packages.chainer.links.connection', 'venv.Lib.site-packages.chainer.links.normalization',
              'venv.Lib.site-packages.chainer.utils', 'venv.Lib.site-packages.chainer.dataset',
              'venv.Lib.site-packages.chainer.testing', 'venv.Lib.site-packages.chainer.backends',
              'venv.Lib.site-packages.chainer.datasets', 'venv.Lib.site-packages.chainer.training',
              'venv.Lib.site-packages.chainer.training.triggers', 'venv.Lib.site-packages.chainer.training.updaters',
              'venv.Lib.site-packages.chainer.training.extensions', 'venv.Lib.site-packages.chainer.exporters',
              'venv.Lib.site-packages.chainer.functions', 'venv.Lib.site-packages.chainer.functions.loss',
              'venv.Lib.site-packages.chainer.functions.math', 'venv.Lib.site-packages.chainer.functions.util',
              'venv.Lib.site-packages.chainer.functions.array', 'venv.Lib.site-packages.chainer.functions.noise',
              'venv.Lib.site-packages.chainer.functions.theano', 'venv.Lib.site-packages.chainer.functions.pooling',
              'venv.Lib.site-packages.chainer.functions.activation',
              'venv.Lib.site-packages.chainer.functions.connection',
              'venv.Lib.site-packages.chainer.functions.evaluation',
              'venv.Lib.site-packages.chainer.functions.normalization', 'venv.Lib.site-packages.chainer.iterators',
              'venv.Lib.site-packages.chainer.optimizers', 'venv.Lib.site-packages.chainer.serializers',
              'venv.Lib.site-packages.chainer.initializers', 'venv.Lib.site-packages.chainer.function_hooks',
              'venv.Lib.site-packages.chainer.optimizer_hooks', 'venv.Lib.site-packages.dateutil',
              'venv.Lib.site-packages.dateutil.tz', 'venv.Lib.site-packages.dateutil.parser',
              'venv.Lib.site-packages.dateutil.zoneinfo', 'venv.Lib.site-packages.markdown',
              'venv.Lib.site-packages.markdown.extensions', 'venv.Lib.site-packages.werkzeug',
              'venv.Lib.site-packages.werkzeug.debug', 'venv.Lib.site-packages.werkzeug.contrib',
              'venv.Lib.site-packages.matplotlib', 'venv.Lib.site-packages.matplotlib.tri',
              'venv.Lib.site-packages.matplotlib.axes', 'venv.Lib.site-packages.matplotlib.cbook',
              'venv.Lib.site-packages.matplotlib.style', 'venv.Lib.site-packages.matplotlib.compat',
              'venv.Lib.site-packages.matplotlib.testing', 'venv.Lib.site-packages.matplotlib.testing._nose',
              'venv.Lib.site-packages.matplotlib.testing._nose.plugins',
              'venv.Lib.site-packages.matplotlib.testing.jpl_units', 'venv.Lib.site-packages.matplotlib.backends',
              'venv.Lib.site-packages.matplotlib.backends.qt_editor', 'venv.Lib.site-packages.matplotlib.sphinxext',
              'venv.Lib.site-packages.matplotlib.projections', 'venv.Lib.site-packages.tensorflow',
              'venv.Lib.site-packages.tensorflow.nn', 'venv.Lib.site-packages.tensorflow.nn.rnn_cell',
              'venv.Lib.site-packages.tensorflow.app', 'venv.Lib.site-packages.tensorflow.core',
              'venv.Lib.site-packages.tensorflow.core.lib', 'venv.Lib.site-packages.tensorflow.core.lib.core',
              'venv.Lib.site-packages.tensorflow.core.util', 'venv.Lib.site-packages.tensorflow.core.example',
              'venv.Lib.site-packages.tensorflow.core.profiler', 'venv.Lib.site-packages.tensorflow.core.protobuf',
              'venv.Lib.site-packages.tensorflow.core.framework', 'venv.Lib.site-packages.tensorflow.data',
              'venv.Lib.site-packages.tensorflow.math', 'venv.Lib.site-packages.tensorflow.sets',
              'venv.Lib.site-packages.tensorflow.test', 'venv.Lib.site-packages.tensorflow.gfile',
              'venv.Lib.site-packages.tensorflow.image', 'venv.Lib.site-packages.tensorflow.keras',
              'venv.Lib.site-packages.tensorflow.keras.utils', 'venv.Lib.site-packages.tensorflow.keras.layers',
              'venv.Lib.site-packages.tensorflow.keras.losses', 'venv.Lib.site-packages.tensorflow.keras.models',
              'venv.Lib.site-packages.tensorflow.keras.backend', 'venv.Lib.site-packages.tensorflow.keras.metrics',
              'venv.Lib.site-packages.tensorflow.keras.datasets',
              'venv.Lib.site-packages.tensorflow.keras.datasets.imdb',
              'venv.Lib.site-packages.tensorflow.keras.datasets.mnist',
              'venv.Lib.site-packages.tensorflow.keras.datasets.cifar10',
              'venv.Lib.site-packages.tensorflow.keras.datasets.reuters',
              'venv.Lib.site-packages.tensorflow.keras.datasets.cifar100',
              'venv.Lib.site-packages.tensorflow.keras.datasets.fashion_mnist',
              'venv.Lib.site-packages.tensorflow.keras.datasets.boston_housing',
              'venv.Lib.site-packages.tensorflow.keras.wrappers',
              'venv.Lib.site-packages.tensorflow.keras.wrappers.scikit_learn',
              'venv.Lib.site-packages.tensorflow.keras.callbacks', 'venv.Lib.site-packages.tensorflow.keras.estimator',
              'venv.Lib.site-packages.tensorflow.keras.optimizers',
              'venv.Lib.site-packages.tensorflow.keras.activations',
              'venv.Lib.site-packages.tensorflow.keras.constraints',
              'venv.Lib.site-packages.tensorflow.keras.applications',
              'venv.Lib.site-packages.tensorflow.keras.applications.vgg16',
              'venv.Lib.site-packages.tensorflow.keras.applications.vgg19',
              'venv.Lib.site-packages.tensorflow.keras.applications.nasnet',
              'venv.Lib.site-packages.tensorflow.keras.applications.densenet',
              'venv.Lib.site-packages.tensorflow.keras.applications.resnet50',
              'venv.Lib.site-packages.tensorflow.keras.applications.xception',
              'venv.Lib.site-packages.tensorflow.keras.applications.mobilenet',
              'venv.Lib.site-packages.tensorflow.keras.applications.inception_v3',
              'venv.Lib.site-packages.tensorflow.keras.applications.inception_resnet_v2',
              'venv.Lib.site-packages.tensorflow.keras.initializers',
              'venv.Lib.site-packages.tensorflow.keras.regularizers',
              'venv.Lib.site-packages.tensorflow.keras.preprocessing',
              'venv.Lib.site-packages.tensorflow.keras.preprocessing.text',
              'venv.Lib.site-packages.tensorflow.keras.preprocessing.image',
              'venv.Lib.site-packages.tensorflow.keras.preprocessing.sequence',
              'venv.Lib.site-packages.tensorflow.manip', 'venv.Lib.site-packages.tensorflow.tools',
              'venv.Lib.site-packages.tensorflow.tools.api', 'venv.Lib.site-packages.tensorflow.tools.api.generator',
              'venv.Lib.site-packages.tensorflow.tools.graph_transforms', 'venv.Lib.site-packages.tensorflow.train',
              'venv.Lib.site-packages.tensorflow.train.queue_runner', 'venv.Lib.site-packages.tensorflow.compat',
              'venv.Lib.site-packages.tensorflow.errors', 'venv.Lib.site-packages.tensorflow.layers',
              'venv.Lib.site-packages.tensorflow.linalg', 'venv.Lib.site-packages.tensorflow.losses',
              'venv.Lib.site-packages.tensorflow.python', 'venv.Lib.site-packages.tensorflow.python.lib',
              'venv.Lib.site-packages.tensorflow.python.lib.io', 'venv.Lib.site-packages.tensorflow.python.lib.core',
              'venv.Lib.site-packages.tensorflow.python.ops', 'venv.Lib.site-packages.tensorflow.python.ops.linalg',
              'venv.Lib.site-packages.tensorflow.python.ops.losses',
              'venv.Lib.site-packages.tensorflow.python.ops.distributions',
              'venv.Lib.site-packages.tensorflow.python.data', 'venv.Lib.site-packages.tensorflow.python.data.ops',
              'venv.Lib.site-packages.tensorflow.python.data.util', 'venv.Lib.site-packages.tensorflow.python.util',
              'venv.Lib.site-packages.tensorflow.python.util.protobuf',
              'venv.Lib.site-packages.tensorflow.python.debug', 'venv.Lib.site-packages.tensorflow.python.debug.cli',
              'venv.Lib.site-packages.tensorflow.python.debug.lib',
              'venv.Lib.site-packages.tensorflow.python.debug.examples',
              'venv.Lib.site-packages.tensorflow.python.debug.wrappers',
              'venv.Lib.site-packages.tensorflow.python.eager', 'venv.Lib.site-packages.tensorflow.python.keras',
              'venv.Lib.site-packages.tensorflow.python.keras.utils',
              'venv.Lib.site-packages.tensorflow.python.keras.engine',
              'venv.Lib.site-packages.tensorflow.python.keras.layers',
              'venv.Lib.site-packages.tensorflow.python.keras.datasets',
              'venv.Lib.site-packages.tensorflow.python.keras.wrappers',
              'venv.Lib.site-packages.tensorflow.python.keras.applications',
              'venv.Lib.site-packages.tensorflow.python.keras.preprocessing',
              'venv.Lib.site-packages.tensorflow.python.tools', 'venv.Lib.site-packages.tensorflow.python.client',
              'venv.Lib.site-packages.tensorflow.python.layers', 'venv.Lib.site-packages.tensorflow.python.summary',
              'venv.Lib.site-packages.tensorflow.python.summary.writer',
              'venv.Lib.site-packages.tensorflow.python.grappler', 'venv.Lib.site-packages.tensorflow.python.platform',
              'venv.Lib.site-packages.tensorflow.python.profiler',
              'venv.Lib.site-packages.tensorflow.python.profiler.internal',
              'venv.Lib.site-packages.tensorflow.python.training',
              'venv.Lib.site-packages.tensorflow.python.training.checkpointable',
              'venv.Lib.site-packages.tensorflow.python.user_ops', 'venv.Lib.site-packages.tensorflow.python.estimator',
              'venv.Lib.site-packages.tensorflow.python.estimator.canned',
              'venv.Lib.site-packages.tensorflow.python.estimator.export',
              'venv.Lib.site-packages.tensorflow.python.estimator.inputs',
              'venv.Lib.site-packages.tensorflow.python.estimator.inputs.queues',
              'venv.Lib.site-packages.tensorflow.python.framework',
              'venv.Lib.site-packages.tensorflow.python.saved_model',
              'venv.Lib.site-packages.tensorflow.python.kernel_tests',
              'venv.Lib.site-packages.tensorflow.python.kernel_tests.linalg',
              'venv.Lib.site-packages.tensorflow.python.kernel_tests.random',
              'venv.Lib.site-packages.tensorflow.python.kernel_tests.testdata',
              'venv.Lib.site-packages.tensorflow.python.kernel_tests.boosted_trees',
              'venv.Lib.site-packages.tensorflow.python.kernel_tests.distributions',
              'venv.Lib.site-packages.tensorflow.python.feature_column', 'venv.Lib.site-packages.tensorflow.sparse',
              'venv.Lib.site-packages.tensorflow.bitwise', 'venv.Lib.site-packages.tensorflow.contrib',
              'venv.Lib.site-packages.tensorflow.contrib.nn', 'venv.Lib.site-packages.tensorflow.contrib.nn.python',
              'venv.Lib.site-packages.tensorflow.contrib.nn.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.crf', 'venv.Lib.site-packages.tensorflow.contrib.crf.python',
              'venv.Lib.site-packages.tensorflow.contrib.crf.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.gan', 'venv.Lib.site-packages.tensorflow.contrib.gan.python',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.eval',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.eval.python',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.losses',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.losses.python',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.features',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.features.python',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.estimator',
              'venv.Lib.site-packages.tensorflow.contrib.gan.python.estimator.python',
              'venv.Lib.site-packages.tensorflow.contrib.opt', 'venv.Lib.site-packages.tensorflow.contrib.opt.python',
              'venv.Lib.site-packages.tensorflow.contrib.opt.python.training',
              'venv.Lib.site-packages.tensorflow.contrib.rnn', 'venv.Lib.site-packages.tensorflow.contrib.rnn.ops',
              'venv.Lib.site-packages.tensorflow.contrib.rnn.python',
              'venv.Lib.site-packages.tensorflow.contrib.rnn.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.rnn.python.kernel_tests',
              'venv.Lib.site-packages.tensorflow.contrib.rnn.kernels', 'venv.Lib.site-packages.tensorflow.contrib.rpc',
              'venv.Lib.site-packages.tensorflow.contrib.rpc.python',
              'venv.Lib.site-packages.tensorflow.contrib.rpc.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tpu', 'venv.Lib.site-packages.tensorflow.contrib.tpu.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.proto',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.python',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.python.tpu',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.python.profiler',
              'venv.Lib.site-packages.tensorflow.contrib.tpu.profiler',
              'venv.Lib.site-packages.tensorflow.contrib.data', 'venv.Lib.site-packages.tensorflow.contrib.data.python',
              'venv.Lib.site-packages.tensorflow.contrib.data.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.data.python.kernel_tests',
              'venv.Lib.site-packages.tensorflow.contrib.data.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.kfac', 'venv.Lib.site-packages.tensorflow.contrib.kfac.python',
              'venv.Lib.site-packages.tensorflow.contrib.kfac.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.kfac.examples',
              'venv.Lib.site-packages.tensorflow.contrib.lite.python', 'venv.Lib.site-packages.tensorflow.contrib.nccl',
              'venv.Lib.site-packages.tensorflow.contrib.nccl.ops',
              'venv.Lib.site-packages.tensorflow.contrib.nccl.python',
              'venv.Lib.site-packages.tensorflow.contrib.nccl.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.nccl.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.slim', 'venv.Lib.site-packages.tensorflow.contrib.slim.python',
              'venv.Lib.site-packages.tensorflow.contrib.slim.python.slim',
              'venv.Lib.site-packages.tensorflow.contrib.slim.python.slim.data',
              'venv.Lib.site-packages.tensorflow.contrib.slim.python.slim.nets',
              'venv.Lib.site-packages.tensorflow.contrib.text', 'venv.Lib.site-packages.tensorflow.contrib.text.ops',
              'venv.Lib.site-packages.tensorflow.contrib.text.python',
              'venv.Lib.site-packages.tensorflow.contrib.text.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.text.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.util', 'venv.Lib.site-packages.tensorflow.contrib.cloud',
              'venv.Lib.site-packages.tensorflow.contrib.cloud.ops',
              'venv.Lib.site-packages.tensorflow.contrib.cloud.python',
              'venv.Lib.site-packages.tensorflow.contrib.cloud.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.cloud.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.coder', 'venv.Lib.site-packages.tensorflow.contrib.coder.ops',
              'venv.Lib.site-packages.tensorflow.contrib.coder.python',
              'venv.Lib.site-packages.tensorflow.contrib.coder.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.coder.python.layers',
              'venv.Lib.site-packages.tensorflow.contrib.coder.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.eager',
              'venv.Lib.site-packages.tensorflow.contrib.eager.python',
              'venv.Lib.site-packages.tensorflow.contrib.hooks',
              'venv.Lib.site-packages.tensorflow.contrib.hooks.python',
              'venv.Lib.site-packages.tensorflow.contrib.image', 'venv.Lib.site-packages.tensorflow.contrib.image.ops',
              'venv.Lib.site-packages.tensorflow.contrib.image.python',
              'venv.Lib.site-packages.tensorflow.contrib.image.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.image.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.kafka.python',
              'venv.Lib.site-packages.tensorflow.contrib.kafka.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.keras', 'venv.Lib.site-packages.tensorflow.contrib.keras.api',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.utils',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.layers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.losses',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.models',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.backend',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.metrics',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.imdb',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.mnist',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.cifar10',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.reuters',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.cifar100',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.datasets.boston_housing',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.wrappers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.wrappers.scikit_learn',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.callbacks',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.optimizers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.activations',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.constraints',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.vgg16',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.vgg19',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.resnet50',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.xception',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.mobilenet',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.applications.inception_v3',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.initializers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.regularizers',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.preprocessing',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.text',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.image',
              'venv.Lib.site-packages.tensorflow.contrib.keras.api.keras.preprocessing.sequence',
              'venv.Lib.site-packages.tensorflow.contrib.learn',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.ops',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.utils',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.datasets',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.datasets.data',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.learn_io',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.estimators',
              'venv.Lib.site-packages.tensorflow.contrib.learn.python.learn.preprocessing',
              'venv.Lib.site-packages.tensorflow.contrib.proto',
              'venv.Lib.site-packages.tensorflow.contrib.proto.python',
              'venv.Lib.site-packages.tensorflow.contrib.proto.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.specs',
              'venv.Lib.site-packages.tensorflow.contrib.specs.python',
              'venv.Lib.site-packages.tensorflow.contrib.ffmpeg',
              'venv.Lib.site-packages.tensorflow.contrib.ffmpeg.default',
              'venv.Lib.site-packages.tensorflow.contrib.layers',
              'venv.Lib.site-packages.tensorflow.contrib.layers.ops',
              'venv.Lib.site-packages.tensorflow.contrib.layers.python',
              'venv.Lib.site-packages.tensorflow.contrib.layers.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.layers.python.layers',
              'venv.Lib.site-packages.tensorflow.contrib.layers.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.libsvm',
              'venv.Lib.site-packages.tensorflow.contrib.libsvm.python',
              'venv.Lib.site-packages.tensorflow.contrib.libsvm.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.libsvm.python.kernel_tests',
              'venv.Lib.site-packages.tensorflow.contrib.linalg',
              'venv.Lib.site-packages.tensorflow.contrib.linalg.python',
              'venv.Lib.site-packages.tensorflow.contrib.linalg.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.lookup', 'venv.Lib.site-packages.tensorflow.contrib.losses',
              'venv.Lib.site-packages.tensorflow.contrib.losses.python',
              'venv.Lib.site-packages.tensorflow.contrib.losses.python.losses',
              'venv.Lib.site-packages.tensorflow.contrib.losses.python.metric_learning',
              'venv.Lib.site-packages.tensorflow.contrib.signal',
              'venv.Lib.site-packages.tensorflow.contrib.signal.python',
              'venv.Lib.site-packages.tensorflow.contrib.signal.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tfprof', 'venv.Lib.site-packages.tensorflow.contrib.android',
              'venv.Lib.site-packages.tensorflow.contrib.android.jni',
              'venv.Lib.site-packages.tensorflow.contrib.android.java',
              'venv.Lib.site-packages.tensorflow.contrib.android.java.org',
              'venv.Lib.site-packages.tensorflow.contrib.android.java.org.tensorflow',
              'venv.Lib.site-packages.tensorflow.contrib.android.java.org.tensorflow.contrib',
              'venv.Lib.site-packages.tensorflow.contrib.android.java.org.tensorflow.contrib.android',
              'venv.Lib.site-packages.tensorflow.contrib.metrics',
              'venv.Lib.site-packages.tensorflow.contrib.metrics.python',
              'venv.Lib.site-packages.tensorflow.contrib.metrics.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.metrics.python.metrics',
              'venv.Lib.site-packages.tensorflow.contrib.seq2seq',
              'venv.Lib.site-packages.tensorflow.contrib.seq2seq.ops',
              'venv.Lib.site-packages.tensorflow.contrib.seq2seq.python',
              'venv.Lib.site-packages.tensorflow.contrib.seq2seq.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.seq2seq.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.solvers',
              'venv.Lib.site-packages.tensorflow.contrib.solvers.python',
              'venv.Lib.site-packages.tensorflow.contrib.solvers.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.staging', 'venv.Lib.site-packages.tensorflow.contrib.summary',
              'venv.Lib.site-packages.tensorflow.contrib.testing',
              'venv.Lib.site-packages.tensorflow.contrib.testing.python',
              'venv.Lib.site-packages.tensorflow.contrib.testing.python.framework',
              'venv.Lib.site-packages.tensorflow.contrib.batching',
              'venv.Lib.site-packages.tensorflow.contrib.batching.python',
              'venv.Lib.site-packages.tensorflow.contrib.batching.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.compiler',
              'venv.Lib.site-packages.tensorflow.contrib.grid_rnn',
              'venv.Lib.site-packages.tensorflow.contrib.grid_rnn.python',
              'venv.Lib.site-packages.tensorflow.contrib.grid_rnn.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.makefile',
              'venv.Lib.site-packages.tensorflow.contrib.quantize',
              'venv.Lib.site-packages.tensorflow.contrib.quantize.python',
              'venv.Lib.site-packages.tensorflow.contrib.training',
              'venv.Lib.site-packages.tensorflow.contrib.training.python',
              'venv.Lib.site-packages.tensorflow.contrib.training.python.training',
              'venv.Lib.site-packages.tensorflow.contrib.bayesflow',
              'venv.Lib.site-packages.tensorflow.contrib.bayesflow.python',
              'venv.Lib.site-packages.tensorflow.contrib.bayesflow.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.cudnn_rnn',
              'venv.Lib.site-packages.tensorflow.contrib.cudnn_rnn.python',
              'venv.Lib.site-packages.tensorflow.contrib.cudnn_rnn.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.cudnn_rnn.python.layers',
              'venv.Lib.site-packages.tensorflow.contrib.estimator',
              'venv.Lib.site-packages.tensorflow.contrib.estimator.python',
              'venv.Lib.site-packages.tensorflow.contrib.estimator.python.estimator',
              'venv.Lib.site-packages.tensorflow.contrib.framework',
              'venv.Lib.site-packages.tensorflow.contrib.framework.ops',
              'venv.Lib.site-packages.tensorflow.contrib.framework.python',
              'venv.Lib.site-packages.tensorflow.contrib.framework.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.framework.python.framework',
              'venv.Lib.site-packages.tensorflow.contrib.framework.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.integrate',
              'venv.Lib.site-packages.tensorflow.contrib.integrate.python',
              'venv.Lib.site-packages.tensorflow.contrib.integrate.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.predictor',
              'venv.Lib.site-packages.tensorflow.contrib.recurrent',
              'venv.Lib.site-packages.tensorflow.contrib.recurrent.python',
              'venv.Lib.site-packages.tensorflow.contrib.recurrent.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.recurrent.python.kernel_tests',
              'venv.Lib.site-packages.tensorflow.contrib.resampler',
              'venv.Lib.site-packages.tensorflow.contrib.resampler.ops',
              'venv.Lib.site-packages.tensorflow.contrib.resampler.python',
              'venv.Lib.site-packages.tensorflow.contrib.resampler.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.resampler.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.sparsemax',
              'venv.Lib.site-packages.tensorflow.contrib.sparsemax.python',
              'venv.Lib.site-packages.tensorflow.contrib.sparsemax.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.stateless',
              'venv.Lib.site-packages.tensorflow.contrib.stateless.python',
              'venv.Lib.site-packages.tensorflow.contrib.all_reduce',
              'venv.Lib.site-packages.tensorflow.contrib.all_reduce.python',
              'venv.Lib.site-packages.tensorflow.contrib.checkpoint',
              'venv.Lib.site-packages.tensorflow.contrib.checkpoint.python',
              'venv.Lib.site-packages.tensorflow.contrib.copy_graph',
              'venv.Lib.site-packages.tensorflow.contrib.copy_graph.python',
              'venv.Lib.site-packages.tensorflow.contrib.copy_graph.python.util',
              'venv.Lib.site-packages.tensorflow.contrib.deprecated',
              'venv.Lib.site-packages.tensorflow.contrib.distribute',
              'venv.Lib.site-packages.tensorflow.contrib.distribute.python',
              'venv.Lib.site-packages.tensorflow.contrib.distribute.python.examples',
              'venv.Lib.site-packages.tensorflow.contrib.fused_conv',
              'venv.Lib.site-packages.tensorflow.contrib.fused_conv.python',
              'venv.Lib.site-packages.tensorflow.contrib.fused_conv.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.fused_conv.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries.python',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries.python.timeseries',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries.python.timeseries.state_space_models',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries.examples',
              'venv.Lib.site-packages.tensorflow.contrib.timeseries.examples.data',
              'venv.Lib.site-packages.tensorflow.contrib.pi_examples',
              'venv.Lib.site-packages.tensorflow.contrib.pi_examples.camera',
              'venv.Lib.site-packages.tensorflow.contrib.pi_examples.label_image',
              'venv.Lib.site-packages.tensorflow.contrib.pi_examples.label_image.data',
              'venv.Lib.site-packages.tensorflow.contrib.saved_model',
              'venv.Lib.site-packages.tensorflow.contrib.saved_model.python',
              'venv.Lib.site-packages.tensorflow.contrib.saved_model.python.saved_model',
              'venv.Lib.site-packages.tensorflow.contrib.tensorboard',
              'venv.Lib.site-packages.tensorflow.contrib.tensorboard.plugins',
              'venv.Lib.site-packages.tensorflow.contrib.tensorboard.plugins.trace',
              'venv.Lib.site-packages.tensorflow.contrib.tensorboard.plugins.projector',
              'venv.Lib.site-packages.tensorflow.contrib.graph_editor',
              'venv.Lib.site-packages.tensorflow.contrib.graph_editor.examples',
              'venv.Lib.site-packages.tensorflow.contrib.memory_stats',
              'venv.Lib.site-packages.tensorflow.contrib.memory_stats.ops',
              'venv.Lib.site-packages.tensorflow.contrib.memory_stats.python',
              'venv.Lib.site-packages.tensorflow.contrib.memory_stats.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.memory_stats.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.optimizer_v2',
              'venv.Lib.site-packages.tensorflow.contrib.quantization',
              'venv.Lib.site-packages.tensorflow.contrib.quantization.python',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.ops',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.proto',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python.utils',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python.training',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python.training.functions',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.python.kernel_tests',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.boosted_trees.estimator_batch',
              'venv.Lib.site-packages.tensorflow.contrib.distributions',
              'venv.Lib.site-packages.tensorflow.contrib.distributions.python',
              'venv.Lib.site-packages.tensorflow.contrib.distributions.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.distributions.python.ops.bijectors',
              'venv.Lib.site-packages.tensorflow.contrib.factorization',
              'venv.Lib.site-packages.tensorflow.contrib.factorization.ops',
              'venv.Lib.site-packages.tensorflow.contrib.factorization.python',
              'venv.Lib.site-packages.tensorflow.contrib.factorization.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.factorization.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.factorization.examples',
              'venv.Lib.site-packages.tensorflow.contrib.model_pruning',
              'venv.Lib.site-packages.tensorflow.contrib.model_pruning.python',
              'venv.Lib.site-packages.tensorflow.contrib.model_pruning.python.layers',
              'venv.Lib.site-packages.tensorflow.contrib.model_pruning.examples',
              'venv.Lib.site-packages.tensorflow.contrib.model_pruning.examples.cifar10',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.proto',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.client',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.core',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.core.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.python',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.layers',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.hybrid.python.models',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.python',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.tensor_forest.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.decision_trees',
              'venv.Lib.site-packages.tensorflow.contrib.decision_trees.proto',
              'venv.Lib.site-packages.tensorflow.contrib.feature_column',
              'venv.Lib.site-packages.tensorflow.contrib.feature_column.python',
              'venv.Lib.site-packages.tensorflow.contrib.feature_column.python.feature_column',
              'venv.Lib.site-packages.tensorflow.contrib.input_pipeline',
              'venv.Lib.site-packages.tensorflow.contrib.input_pipeline.ops',
              'venv.Lib.site-packages.tensorflow.contrib.input_pipeline.python',
              'venv.Lib.site-packages.tensorflow.contrib.input_pipeline.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.input_pipeline.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.kernel_methods',
              'venv.Lib.site-packages.tensorflow.contrib.kernel_methods.python',
              'venv.Lib.site-packages.tensorflow.contrib.kernel_methods.python.mappers',
              'venv.Lib.site-packages.tensorflow.contrib.labeled_tensor',
              'venv.Lib.site-packages.tensorflow.contrib.labeled_tensor.python',
              'venv.Lib.site-packages.tensorflow.contrib.labeled_tensor.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.legacy_seq2seq',
              'venv.Lib.site-packages.tensorflow.contrib.legacy_seq2seq.python',
              'venv.Lib.site-packages.tensorflow.contrib.legacy_seq2seq.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.session_bundle',
              'venv.Lib.site-packages.tensorflow.contrib.session_bundle.example',
              'venv.Lib.site-packages.tensorflow.contrib.mixed_precision',
              'venv.Lib.site-packages.tensorflow.contrib.mixed_precision.python',
              'venv.Lib.site-packages.tensorflow.contrib.mpi_collectives.python',
              'venv.Lib.site-packages.tensorflow.contrib.mpi_collectives.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.receptive_field',
              'venv.Lib.site-packages.tensorflow.contrib.receptive_field.python',
              'venv.Lib.site-packages.tensorflow.contrib.receptive_field.python.util',
              'venv.Lib.site-packages.tensorflow.contrib.receptive_field.python.util.examples',
              'venv.Lib.site-packages.tensorflow.contrib.stat_summarizer',
              'venv.Lib.site-packages.tensorflow.contrib.stat_summarizer.python',
              'venv.Lib.site-packages.tensorflow.contrib.cluster_resolver',
              'venv.Lib.site-packages.tensorflow.contrib.cluster_resolver.python',
              'venv.Lib.site-packages.tensorflow.contrib.cluster_resolver.python.training',
              'venv.Lib.site-packages.tensorflow.contrib.linear_optimizer',
              'venv.Lib.site-packages.tensorflow.contrib.linear_optimizer.python',
              'venv.Lib.site-packages.tensorflow.contrib.linear_optimizer.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.linear_optimizer.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.linear_optimizer.kernels.g3doc',
              'venv.Lib.site-packages.tensorflow.contrib.nearest_neighbor',
              'venv.Lib.site-packages.tensorflow.contrib.nearest_neighbor.ops',
              'venv.Lib.site-packages.tensorflow.contrib.nearest_neighbor.python',
              'venv.Lib.site-packages.tensorflow.contrib.nearest_neighbor.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.nearest_neighbor.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.reduce_slice_ops',
              'venv.Lib.site-packages.tensorflow.contrib.reduce_slice_ops.ops',
              'venv.Lib.site-packages.tensorflow.contrib.reduce_slice_ops.python',
              'venv.Lib.site-packages.tensorflow.contrib.reduce_slice_ops.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.reduce_slice_ops.kernels',
              'venv.Lib.site-packages.tensorflow.contrib.periodic_resample',
              'venv.Lib.site-packages.tensorflow.contrib.periodic_resample.python',
              'venv.Lib.site-packages.tensorflow.contrib.periodic_resample.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.remote_fused_graph',
              'venv.Lib.site-packages.tensorflow.contrib.remote_fused_graph.pylib',
              'venv.Lib.site-packages.tensorflow.contrib.remote_fused_graph.pylib.python',
              'venv.Lib.site-packages.tensorflow.contrib.remote_fused_graph.pylib.python.ops',
              'venv.Lib.site-packages.tensorflow.contrib.meta_graph_transform',
              'venv.Lib.site-packages.tensorflow.contrib.constrained_optimization',
              'venv.Lib.site-packages.tensorflow.contrib.constrained_optimization.python',
              'venv.Lib.site-packages.tensorflow.logging', 'venv.Lib.site-packages.tensorflow.metrics',
              'venv.Lib.site-packages.tensorflow.strings', 'venv.Lib.site-packages.tensorflow.summary',
              'venv.Lib.site-packages.tensorflow.examples', 'venv.Lib.site-packages.tensorflow.examples.tutorials',
              'venv.Lib.site-packages.tensorflow.examples.tutorials.mnist',
              'venv.Lib.site-packages.tensorflow.profiler', 'venv.Lib.site-packages.tensorflow.spectral',
              'venv.Lib.site-packages.tensorflow.user_ops', 'venv.Lib.site-packages.tensorflow.estimator',
              'venv.Lib.site-packages.tensorflow.estimator.export',
              'venv.Lib.site-packages.tensorflow.estimator.inputs', 'venv.Lib.site-packages.tensorflow.python_io',
              'venv.Lib.site-packages.tensorflow.sysconfig', 'venv.Lib.site-packages.tensorflow.graph_util',
              'venv.Lib.site-packages.tensorflow.saved_model', 'venv.Lib.site-packages.tensorflow.saved_model.utils',
              'venv.Lib.site-packages.tensorflow.saved_model.loader',
              'venv.Lib.site-packages.tensorflow.saved_model.builder',
              'venv.Lib.site-packages.tensorflow.saved_model.main_op',
              'venv.Lib.site-packages.tensorflow.saved_model.constants',
              'venv.Lib.site-packages.tensorflow.saved_model.tag_constants',
              'venv.Lib.site-packages.tensorflow.saved_model.signature_constants',
              'venv.Lib.site-packages.tensorflow.saved_model.signature_def_utils',
              'venv.Lib.site-packages.tensorflow.initializers', 'venv.Lib.site-packages.tensorflow.distributions',
              'venv.Lib.site-packages.tensorflow.distributions.bijectors',
              'venv.Lib.site-packages.tensorflow.feature_column', 'venv.Lib.site-packages.tensorflow.resource_loader',
              'venv.Lib.site-packages.tensorboard', 'venv.Lib.site-packages.tensorboard._vendor',
              'venv.Lib.site-packages.tensorboard._vendor.bleach',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.trie',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.filters',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.serializer',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.tensorboard._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.tensorboard.backend',
              'venv.Lib.site-packages.tensorboard.backend.event_processing',
              'venv.Lib.site-packages.tensorboard.plugins', 'venv.Lib.site-packages.tensorboard.plugins.core',
              'venv.Lib.site-packages.tensorboard.plugins.text', 'venv.Lib.site-packages.tensorboard.plugins.audio',
              'venv.Lib.site-packages.tensorboard.plugins.graph', 'venv.Lib.site-packages.tensorboard.plugins.image',
              'venv.Lib.site-packages.tensorboard.plugins.scalar', 'venv.Lib.site-packages.tensorboard.plugins.profile',
              'venv.Lib.site-packages.tensorboard.plugins.beholder',
              'venv.Lib.site-packages.tensorboard.plugins.debugger',
              'venv.Lib.site-packages.tensorboard.plugins.pr_curve',
              'venv.Lib.site-packages.tensorboard.plugins.histogram',
              'venv.Lib.site-packages.tensorboard.plugins.projector',
              'venv.Lib.site-packages.tensorboard.plugins.distribution',
              'venv.Lib.site-packages.tensorboard.plugins.custom_scalar', 'venv.Lib.site-packages.mpl_toolkits.mplot3d',
              'venv.Lib.site-packages.mpl_toolkits.axes_grid', 'venv.Lib.site-packages.mpl_toolkits.axes_grid1',
              'venv.Lib.site-packages.mpl_toolkits.axisartist', 'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.5.egg.pip._internal.operations'],
    url='',
    license='',
    author='mxin',
    author_email='',
    description=''
)
